
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analizadores;

/** CUP generated class containing symbol constants. */
public class Simbolo_R {
  /* terminals */
  public static final int mostrar_ventana = 43;
  public static final int menos = 72;
  public static final int menor = 84;
  public static final int identificador = 93;
  public static final int etiqueta = 38;
  public static final int reservar = 27;
  public static final int abrir = 33;
  public static final int punto = 82;
  public static final int Upor = 95;
  public static final int nulo = 11;
  public static final int concatenar = 29;
  public static final int importar = 8;
  public static final int menosplus = 78;
  public static final int setalto = 57;
  public static final int abrirllave = 65;
  public static final int div = 74;
  public static final int boton = 44;
  public static final int pesode = 26;
  public static final int getancho = 61;
  public static final int romper = 20;
  public static final int tipoboleano = 50;
  public static final int mas = 71;
  public static final int cadena = 4;
  public static final int abrircorchete = 69;
  public static final int dospuntos = 91;
  public static final int menorigual = 86;
  public static final int click = 53;
  public static final int mientras = 15;
  public static final int imprimir = 9;
  public static final int Umenos = 94;
  public static final int sino = 13;
  public static final int decimal = 3;
  public static final int caso = 18;
  public static final int getalto = 62;
  public static final int cerrarllave = 66;
  public static final int principal = 47;
  public static final int settexto = 56;
  public static final int definir = 22;
  public static final int notlogico = 81;
  public static final int caracter = 7;
  public static final int mayorigual = 85;
  public static final int hacermientras = 16;
  public static final int cerrar = 35;
  public static final int regresar = 24;
  public static final int siga = 21;
  public static final int aentero = 30;
  public static final int cajatexto = 39;
  public static final int seleccion = 17;
  public static final int adecimal = 31;
  public static final int vacio = 10;
  public static final int puntocoma = 90;
  public static final int mayor = 83;
  public static final int ciclofor = 14;
  public static final int cadenaR = 46;
  public static final int multiplicacionlogica = 80;
  public static final int iniciar = 52;
  public static final int compequals = 32;
  public static final int buscar_abrir = 36;
  public static final int EOF = 0;
  public static final int escribir = 34;
  public static final int cuando = 25;
  public static final int leer = 37;
  public static final int agregar_componente = 54;
  public static final int falso = 5;
  public static final int cajaareatexto = 40;
  public static final int potencia = 75;
  public static final int atexto = 28;
  public static final int cajanumero = 42;
  public static final int verdadero = 6;
  public static final int error = 1;
  public static final int numeral = 92;
  public static final int diferente = 88;
  public static final int si = 12;
  public static final int setancho = 58;
  public static final int gettexto = 60;
  public static final int tipoentero = 48;
  public static final int mensaje = 45;
  public static final int entero = 2;
  public static final int tipocaracter = 51;
  public static final int setpos = 59;
  public static final int cerrarparentesis = 68;
  public static final int igualigual = 87;
  public static final int defecto = 19;
  public static final int por = 73;
  public static final int coma = 89;
  public static final int sumalogica = 79;
  public static final int modulo = 76;
  public static final int igual = 64;
  public static final int getpos = 63;
  public static final int tipodecimal = 49;
  public static final int cerrarcorchete = 70;
  public static final int masplus = 77;
  public static final int contrasena = 41;
  public static final int fusion = 23;
  public static final int tamform = 55;
  public static final int abrirparentesis = 67;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "entero",
  "decimal",
  "cadena",
  "falso",
  "verdadero",
  "caracter",
  "importar",
  "imprimir",
  "vacio",
  "nulo",
  "si",
  "sino",
  "ciclofor",
  "mientras",
  "hacermientras",
  "seleccion",
  "caso",
  "defecto",
  "romper",
  "siga",
  "definir",
  "fusion",
  "regresar",
  "cuando",
  "pesode",
  "reservar",
  "atexto",
  "concatenar",
  "aentero",
  "adecimal",
  "compequals",
  "abrir",
  "escribir",
  "cerrar",
  "buscar_abrir",
  "leer",
  "etiqueta",
  "cajatexto",
  "cajaareatexto",
  "contrasena",
  "cajanumero",
  "mostrar_ventana",
  "boton",
  "mensaje",
  "cadenaR",
  "principal",
  "tipoentero",
  "tipodecimal",
  "tipoboleano",
  "tipocaracter",
  "iniciar",
  "click",
  "agregar_componente",
  "tamform",
  "settexto",
  "setalto",
  "setancho",
  "setpos",
  "gettexto",
  "getancho",
  "getalto",
  "getpos",
  "igual",
  "abrirllave",
  "cerrarllave",
  "abrirparentesis",
  "cerrarparentesis",
  "abrircorchete",
  "cerrarcorchete",
  "mas",
  "menos",
  "por",
  "div",
  "potencia",
  "modulo",
  "masplus",
  "menosplus",
  "sumalogica",
  "multiplicacionlogica",
  "notlogico",
  "punto",
  "mayor",
  "menor",
  "mayorigual",
  "menorigual",
  "igualigual",
  "diferente",
  "coma",
  "puntocoma",
  "dospuntos",
  "numeral",
  "identificador",
  "Umenos",
  "Upor"
  };
}

