
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analizadores;

/** CUP generated class containing symbol constants. */
public class Simbolo_OLC {
  /* terminals */
  public static final int ruta = 3;
  public static final int coma = 13;
  public static final int cerrarllave = 12;
  public static final int proyecto = 2;
  public static final int cadena = 10;
  public static final int EOF = 0;
  public static final int conf = 6;
  public static final int dospuntos = 14;
  public static final int error = 1;
  public static final int correr = 5;
  public static final int carpeta = 9;
  public static final int archivo = 7;
  public static final int abrirllave = 11;
  public static final int fecha = 8;
  public static final int nombre = 4;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "proyecto",
  "ruta",
  "nombre",
  "correr",
  "conf",
  "archivo",
  "fecha",
  "carpeta",
  "cadena",
  "abrirllave",
  "cerrarllave",
  "coma",
  "dospuntos"
  };
}

