
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analizadores;

import Arbol_OLC.Entorno.Errores_OLC;
import java.util.LinkedList;
import java_cup.runtime.*;
import Arbol_OLC.Instrucciones.*;
import Arbol_OLC.*;
import java_cup.runtime.XMLElement;

/** CUP v0.11b 20160615 (GIT 4ac7450) generated parser.
  */
@SuppressWarnings({"rawtypes"})
public class Sintactico_O extends java_cup.runtime.lr_parser {

 public final Class getSymbolContainer() {
    return Simbolo_O.class;
}

  /** Default constructor. */
  @Deprecated
  public Sintactico_O() {super();}

  /** Constructor which sets the default scanner. */
  @Deprecated
  public Sintactico_O(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public Sintactico_O(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\027\000\002\002\004\000\002\002\005\000\002\003" +
    "\007\000\002\004\005\000\002\004\003\000\002\005\005" +
    "\000\002\005\005\000\002\005\005\000\002\005\007\000" +
    "\002\005\006\000\002\006\005\000\002\006\003\000\002" +
    "\007\003\000\002\007\003\000\002\010\007\000\002\012" +
    "\005\000\002\012\003\000\002\013\005\000\002\013\005" +
    "\000\002\011\013\000\002\011\013\000\002\011\011\000" +
    "\002\011\012" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\101\000\004\015\004\001\002\000\004\004\010\001" +
    "\002\000\004\002\006\001\002\000\004\002\001\001\002" +
    "\000\004\016\103\001\002\000\004\020\011\001\002\000" +
    "\004\015\012\001\002\000\012\005\017\006\020\007\014" +
    "\010\015\001\002\000\006\016\ufffd\017\ufffd\001\002\000" +
    "\004\020\101\001\002\000\004\020\030\001\002\000\006" +
    "\016\026\017\025\001\002\000\004\020\023\001\002\000" +
    "\004\020\021\001\002\000\004\014\022\001\002\000\006" +
    "\016\ufffb\017\ufffb\001\002\000\004\014\024\001\002\000" +
    "\006\016\ufffc\017\ufffc\001\002\000\012\005\017\006\020" +
    "\007\014\010\015\001\002\000\004\016\uffff\001\002\000" +
    "\006\016\ufffe\017\ufffe\001\002\000\004\015\031\001\002" +
    "\000\010\011\035\013\040\016\036\001\002\000\006\016" +
    "\ufff5\017\ufff5\001\002\000\006\016\100\017\053\001\002" +
    "\000\006\016\ufff4\017\ufff4\001\002\000\004\020\063\001" +
    "\002\000\006\016\ufff8\017\ufff8\001\002\000\006\016\ufff6" +
    "\017\ufff6\001\002\000\004\020\041\001\002\000\004\015" +
    "\042\001\002\000\010\006\044\011\035\013\040\001\002" +
    "\000\004\017\056\001\002\000\004\020\045\001\002\000" +
    "\004\014\046\001\002\000\006\016\050\017\047\001\002" +
    "\000\010\011\035\013\040\016\052\001\002\000\006\016" +
    "\uffec\017\uffec\001\002\000\006\016\054\017\053\001\002" +
    "\000\006\016\uffeb\017\uffeb\001\002\000\006\011\035\013" +
    "\040\001\002\000\006\016\uffee\017\uffee\001\002\000\006" +
    "\016\ufff7\017\ufff7\001\002\000\010\006\057\011\035\013" +
    "\040\001\002\000\004\020\060\001\002\000\004\014\061" +
    "\001\002\000\004\016\062\001\002\000\006\016\uffed\017" +
    "\uffed\001\002\000\004\015\064\001\002\000\006\006\067" +
    "\012\065\001\002\000\004\020\076\001\002\000\006\016" +
    "\ufff1\017\ufff1\001\002\000\004\020\074\001\002\000\006" +
    "\016\072\017\071\001\002\000\006\006\067\012\065\001" +
    "\002\000\006\016\ufff3\017\ufff3\001\002\000\006\016\ufff2" +
    "\017\ufff2\001\002\000\004\014\075\001\002\000\006\016" +
    "\ufff0\017\ufff0\001\002\000\004\014\077\001\002\000\006" +
    "\016\uffef\017\uffef\001\002\000\006\016\ufff9\017\ufff9\001" +
    "\002\000\004\014\102\001\002\000\006\016\ufffa\017\ufffa" +
    "\001\002\000\004\002\000\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\101\000\004\002\004\001\001\000\004\003\006\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\006\004\015\005" +
    "\012\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\004\005\026\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\012\006\032" +
    "\007\036\010\031\011\033\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\012\006\042\007\036\010\031\011\033\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\012\006\050\007\036\010\031\011\033" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\010\007\054\010\031\011\033\001\001\000\002" +
    "\001\001\000\002\001\001\000\010\007\054\010\031\011" +
    "\033\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\006\012" +
    "\067\013\065\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\004\013\072\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$Sintactico_O$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$Sintactico_O$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$Sintactico_O$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}


   

    public Arbol_OLC AST;
    public void syntax_error(Symbol s){ 
            Errores_OLC.agregar_error("Error de Orden de sentencia: "+s.value,s.left, s.right,"Sintactico");
            System.err.println("Error Sintactico en la Linea " + (s.left) +" Columna "+s.right+ ". No se esperaba este componente: " +s.value+"."); 
    } 
    public void unrecovered_syntax_error(Symbol s) throws java.lang.Exception{ 
            System.err.println("Error sintactico irrecuperable en la Linea " + (s.left)+ " Columna "+s.right+". Componente " + s.value + " no reconocido."); 
    }  


/** Cup generated class to encapsulate user supplied action code.*/
@SuppressWarnings({"rawtypes", "unchecked", "unused"})
class CUP$Sintactico_O$actions {
  private final Sintactico_O parser;

  /** Constructor */
  CUP$Sintactico_O$actions(Sintactico_O parser) {
    this.parser = parser;
  }

  /** Method 0 with the actual generated action code for actions 0 to 300. */
  public final java_cup.runtime.Symbol CUP$Sintactico_O$do_action_part00000000(
    int                        CUP$Sintactico_O$act_num,
    java_cup.runtime.lr_parser CUP$Sintactico_O$parser,
    java.util.Stack            CUP$Sintactico_O$stack,
    int                        CUP$Sintactico_O$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$Sintactico_O$result;

      /* select the action based on the action number */
      switch (CUP$Sintactico_O$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= INICIO EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$Sintactico_O$stack.elementAt(CUP$Sintactico_O$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$Sintactico_O$stack.elementAt(CUP$Sintactico_O$top-1)).right;
		Instruccion start_val = (Instruccion)((java_cup.runtime.Symbol) CUP$Sintactico_O$stack.elementAt(CUP$Sintactico_O$top-1)).value;
		RESULT = start_val;
              CUP$Sintactico_O$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$Sintactico_O$stack.elementAt(CUP$Sintactico_O$top-1)), ((java_cup.runtime.Symbol)CUP$Sintactico_O$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$Sintactico_O$parser.done_parsing();
          return CUP$Sintactico_O$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // INICIO ::= abrirllave CUERPO cerrarllave 
            {
              Instruccion RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$Sintactico_O$stack.elementAt(CUP$Sintactico_O$top-1)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$Sintactico_O$stack.elementAt(CUP$Sintactico_O$top-1)).right;
		Instruccion a = (Instruccion)((java_cup.runtime.Symbol) CUP$Sintactico_O$stack.elementAt(CUP$Sintactico_O$top-1)).value;
		AST=new Arbol_OLC(a);
              CUP$Sintactico_O$result = parser.getSymbolFactory().newSymbol("INICIO",0, ((java_cup.runtime.Symbol)CUP$Sintactico_O$stack.elementAt(CUP$Sintactico_O$top-2)), ((java_cup.runtime.Symbol)CUP$Sintactico_O$stack.peek()), RESULT);
            }
          return CUP$Sintactico_O$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // CUERPO ::= proyecto dospuntos abrirllave CUERPOPROYECTO cerrarllave 
            {
              Instruccion RESULT =null;
		int bleft = ((java_cup.runtime.Symbol)CUP$Sintactico_O$stack.elementAt(CUP$Sintactico_O$top-4)).left;
		int bright = ((java_cup.runtime.Symbol)CUP$Sintactico_O$stack.elementAt(CUP$Sintactico_O$top-4)).right;
		String b = (String)((java_cup.runtime.Symbol) CUP$Sintactico_O$stack.elementAt(CUP$Sintactico_O$top-4)).value;
		int aleft = ((java_cup.runtime.Symbol)CUP$Sintactico_O$stack.elementAt(CUP$Sintactico_O$top-1)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$Sintactico_O$stack.elementAt(CUP$Sintactico_O$top-1)).right;
		LinkedList<Instruccion> a = (LinkedList<Instruccion>)((java_cup.runtime.Symbol) CUP$Sintactico_O$stack.elementAt(CUP$Sintactico_O$top-1)).value;
		RESULT = new PROYECTO(a,bleft,aright);
              CUP$Sintactico_O$result = parser.getSymbolFactory().newSymbol("CUERPO",1, ((java_cup.runtime.Symbol)CUP$Sintactico_O$stack.elementAt(CUP$Sintactico_O$top-4)), ((java_cup.runtime.Symbol)CUP$Sintactico_O$stack.peek()), RESULT);
            }
          return CUP$Sintactico_O$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // CUERPOPROYECTO ::= CUERPOPROYECTO coma PROPIEDAD 
            {
              LinkedList<Instruccion> RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$Sintactico_O$stack.elementAt(CUP$Sintactico_O$top-2)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$Sintactico_O$stack.elementAt(CUP$Sintactico_O$top-2)).right;
		LinkedList<Instruccion> a = (LinkedList<Instruccion>)((java_cup.runtime.Symbol) CUP$Sintactico_O$stack.elementAt(CUP$Sintactico_O$top-2)).value;
		int bleft = ((java_cup.runtime.Symbol)CUP$Sintactico_O$stack.peek()).left;
		int bright = ((java_cup.runtime.Symbol)CUP$Sintactico_O$stack.peek()).right;
		Instruccion b = (Instruccion)((java_cup.runtime.Symbol) CUP$Sintactico_O$stack.peek()).value;
		RESULT=a; RESULT.add(b);
              CUP$Sintactico_O$result = parser.getSymbolFactory().newSymbol("CUERPOPROYECTO",2, ((java_cup.runtime.Symbol)CUP$Sintactico_O$stack.elementAt(CUP$Sintactico_O$top-2)), ((java_cup.runtime.Symbol)CUP$Sintactico_O$stack.peek()), RESULT);
            }
          return CUP$Sintactico_O$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // CUERPOPROYECTO ::= PROPIEDAD 
            {
              LinkedList<Instruccion> RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$Sintactico_O$stack.peek()).left;
		int aright = ((java_cup.runtime.Symbol)CUP$Sintactico_O$stack.peek()).right;
		Instruccion a = (Instruccion)((java_cup.runtime.Symbol) CUP$Sintactico_O$stack.peek()).value;
		RESULT = new LinkedList(); RESULT.add(a);
              CUP$Sintactico_O$result = parser.getSymbolFactory().newSymbol("CUERPOPROYECTO",2, ((java_cup.runtime.Symbol)CUP$Sintactico_O$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico_O$stack.peek()), RESULT);
            }
          return CUP$Sintactico_O$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // PROPIEDAD ::= ruta dospuntos cadena 
            {
              Instruccion RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$Sintactico_O$stack.elementAt(CUP$Sintactico_O$top-2)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$Sintactico_O$stack.elementAt(CUP$Sintactico_O$top-2)).right;
		String a = (String)((java_cup.runtime.Symbol) CUP$Sintactico_O$stack.elementAt(CUP$Sintactico_O$top-2)).value;
		int bleft = ((java_cup.runtime.Symbol)CUP$Sintactico_O$stack.peek()).left;
		int bright = ((java_cup.runtime.Symbol)CUP$Sintactico_O$stack.peek()).right;
		String b = (String)((java_cup.runtime.Symbol) CUP$Sintactico_O$stack.peek()).value;
		RESULT = new PROPIEDAD(a,b,aleft,aright);
              CUP$Sintactico_O$result = parser.getSymbolFactory().newSymbol("PROPIEDAD",3, ((java_cup.runtime.Symbol)CUP$Sintactico_O$stack.elementAt(CUP$Sintactico_O$top-2)), ((java_cup.runtime.Symbol)CUP$Sintactico_O$stack.peek()), RESULT);
            }
          return CUP$Sintactico_O$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // PROPIEDAD ::= nombre dospuntos cadena 
            {
              Instruccion RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$Sintactico_O$stack.elementAt(CUP$Sintactico_O$top-2)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$Sintactico_O$stack.elementAt(CUP$Sintactico_O$top-2)).right;
		String a = (String)((java_cup.runtime.Symbol) CUP$Sintactico_O$stack.elementAt(CUP$Sintactico_O$top-2)).value;
		int bleft = ((java_cup.runtime.Symbol)CUP$Sintactico_O$stack.peek()).left;
		int bright = ((java_cup.runtime.Symbol)CUP$Sintactico_O$stack.peek()).right;
		String b = (String)((java_cup.runtime.Symbol) CUP$Sintactico_O$stack.peek()).value;
		RESULT = new PROPIEDAD(a,b,aleft,aright);
              CUP$Sintactico_O$result = parser.getSymbolFactory().newSymbol("PROPIEDAD",3, ((java_cup.runtime.Symbol)CUP$Sintactico_O$stack.elementAt(CUP$Sintactico_O$top-2)), ((java_cup.runtime.Symbol)CUP$Sintactico_O$stack.peek()), RESULT);
            }
          return CUP$Sintactico_O$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // PROPIEDAD ::= correr dospuntos cadena 
            {
              Instruccion RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$Sintactico_O$stack.elementAt(CUP$Sintactico_O$top-2)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$Sintactico_O$stack.elementAt(CUP$Sintactico_O$top-2)).right;
		String a = (String)((java_cup.runtime.Symbol) CUP$Sintactico_O$stack.elementAt(CUP$Sintactico_O$top-2)).value;
		int bleft = ((java_cup.runtime.Symbol)CUP$Sintactico_O$stack.peek()).left;
		int bright = ((java_cup.runtime.Symbol)CUP$Sintactico_O$stack.peek()).right;
		String b = (String)((java_cup.runtime.Symbol) CUP$Sintactico_O$stack.peek()).value;
		RESULT = new PROPIEDAD(a,b,aleft,aright);
              CUP$Sintactico_O$result = parser.getSymbolFactory().newSymbol("PROPIEDAD",3, ((java_cup.runtime.Symbol)CUP$Sintactico_O$stack.elementAt(CUP$Sintactico_O$top-2)), ((java_cup.runtime.Symbol)CUP$Sintactico_O$stack.peek()), RESULT);
            }
          return CUP$Sintactico_O$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // PROPIEDAD ::= conf dospuntos abrirllave DIRECTORIOS cerrarllave 
            {
              Instruccion RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$Sintactico_O$stack.elementAt(CUP$Sintactico_O$top-4)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$Sintactico_O$stack.elementAt(CUP$Sintactico_O$top-4)).right;
		String a = (String)((java_cup.runtime.Symbol) CUP$Sintactico_O$stack.elementAt(CUP$Sintactico_O$top-4)).value;
		int bleft = ((java_cup.runtime.Symbol)CUP$Sintactico_O$stack.elementAt(CUP$Sintactico_O$top-1)).left;
		int bright = ((java_cup.runtime.Symbol)CUP$Sintactico_O$stack.elementAt(CUP$Sintactico_O$top-1)).right;
		LinkedList<Instruccion> b = (LinkedList<Instruccion>)((java_cup.runtime.Symbol) CUP$Sintactico_O$stack.elementAt(CUP$Sintactico_O$top-1)).value;
		RESULT = new PROPIEDAD(a,b,aleft,aright);
              CUP$Sintactico_O$result = parser.getSymbolFactory().newSymbol("PROPIEDAD",3, ((java_cup.runtime.Symbol)CUP$Sintactico_O$stack.elementAt(CUP$Sintactico_O$top-4)), ((java_cup.runtime.Symbol)CUP$Sintactico_O$stack.peek()), RESULT);
            }
          return CUP$Sintactico_O$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // PROPIEDAD ::= conf dospuntos abrirllave cerrarllave 
            {
              Instruccion RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$Sintactico_O$stack.elementAt(CUP$Sintactico_O$top-3)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$Sintactico_O$stack.elementAt(CUP$Sintactico_O$top-3)).right;
		String a = (String)((java_cup.runtime.Symbol) CUP$Sintactico_O$stack.elementAt(CUP$Sintactico_O$top-3)).value;
		RESULT = new PROPIEDAD(a,aleft,aright);
              CUP$Sintactico_O$result = parser.getSymbolFactory().newSymbol("PROPIEDAD",3, ((java_cup.runtime.Symbol)CUP$Sintactico_O$stack.elementAt(CUP$Sintactico_O$top-3)), ((java_cup.runtime.Symbol)CUP$Sintactico_O$stack.peek()), RESULT);
            }
          return CUP$Sintactico_O$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // DIRECTORIOS ::= DIRECTORIOS coma ELEMENTO 
            {
              LinkedList<Instruccion> RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$Sintactico_O$stack.elementAt(CUP$Sintactico_O$top-2)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$Sintactico_O$stack.elementAt(CUP$Sintactico_O$top-2)).right;
		LinkedList<Instruccion> a = (LinkedList<Instruccion>)((java_cup.runtime.Symbol) CUP$Sintactico_O$stack.elementAt(CUP$Sintactico_O$top-2)).value;
		int bleft = ((java_cup.runtime.Symbol)CUP$Sintactico_O$stack.peek()).left;
		int bright = ((java_cup.runtime.Symbol)CUP$Sintactico_O$stack.peek()).right;
		Instruccion b = (Instruccion)((java_cup.runtime.Symbol) CUP$Sintactico_O$stack.peek()).value;
		RESULT=a; RESULT.add(b);
              CUP$Sintactico_O$result = parser.getSymbolFactory().newSymbol("DIRECTORIOS",4, ((java_cup.runtime.Symbol)CUP$Sintactico_O$stack.elementAt(CUP$Sintactico_O$top-2)), ((java_cup.runtime.Symbol)CUP$Sintactico_O$stack.peek()), RESULT);
            }
          return CUP$Sintactico_O$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // DIRECTORIOS ::= ELEMENTO 
            {
              LinkedList<Instruccion> RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$Sintactico_O$stack.peek()).left;
		int aright = ((java_cup.runtime.Symbol)CUP$Sintactico_O$stack.peek()).right;
		Instruccion a = (Instruccion)((java_cup.runtime.Symbol) CUP$Sintactico_O$stack.peek()).value;
		RESULT = new LinkedList(); RESULT.add(a);
              CUP$Sintactico_O$result = parser.getSymbolFactory().newSymbol("DIRECTORIOS",4, ((java_cup.runtime.Symbol)CUP$Sintactico_O$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico_O$stack.peek()), RESULT);
            }
          return CUP$Sintactico_O$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // ELEMENTO ::= ARCHIVO 
            {
              Instruccion RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$Sintactico_O$stack.peek()).left;
		int aright = ((java_cup.runtime.Symbol)CUP$Sintactico_O$stack.peek()).right;
		Instruccion a = (Instruccion)((java_cup.runtime.Symbol) CUP$Sintactico_O$stack.peek()).value;
		RESULT= a;
              CUP$Sintactico_O$result = parser.getSymbolFactory().newSymbol("ELEMENTO",5, ((java_cup.runtime.Symbol)CUP$Sintactico_O$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico_O$stack.peek()), RESULT);
            }
          return CUP$Sintactico_O$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // ELEMENTO ::= CARPETA 
            {
              Instruccion RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$Sintactico_O$stack.peek()).left;
		int aright = ((java_cup.runtime.Symbol)CUP$Sintactico_O$stack.peek()).right;
		Instruccion a = (Instruccion)((java_cup.runtime.Symbol) CUP$Sintactico_O$stack.peek()).value;
		RESULT= a;
              CUP$Sintactico_O$result = parser.getSymbolFactory().newSymbol("ELEMENTO",5, ((java_cup.runtime.Symbol)CUP$Sintactico_O$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico_O$stack.peek()), RESULT);
            }
          return CUP$Sintactico_O$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // ARCHIVO ::= archivo dospuntos abrirllave CONFARCHIVO cerrarllave 
            {
              Instruccion RESULT =null;
		int bleft = ((java_cup.runtime.Symbol)CUP$Sintactico_O$stack.elementAt(CUP$Sintactico_O$top-4)).left;
		int bright = ((java_cup.runtime.Symbol)CUP$Sintactico_O$stack.elementAt(CUP$Sintactico_O$top-4)).right;
		String b = (String)((java_cup.runtime.Symbol) CUP$Sintactico_O$stack.elementAt(CUP$Sintactico_O$top-4)).value;
		int aleft = ((java_cup.runtime.Symbol)CUP$Sintactico_O$stack.elementAt(CUP$Sintactico_O$top-1)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$Sintactico_O$stack.elementAt(CUP$Sintactico_O$top-1)).right;
		LinkedList<Instruccion> a = (LinkedList<Instruccion>)((java_cup.runtime.Symbol) CUP$Sintactico_O$stack.elementAt(CUP$Sintactico_O$top-1)).value;
		RESULT = new ARCHIVO(a,bleft,bright);
              CUP$Sintactico_O$result = parser.getSymbolFactory().newSymbol("ARCHIVO",6, ((java_cup.runtime.Symbol)CUP$Sintactico_O$stack.elementAt(CUP$Sintactico_O$top-4)), ((java_cup.runtime.Symbol)CUP$Sintactico_O$stack.peek()), RESULT);
            }
          return CUP$Sintactico_O$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // CONFARCHIVO ::= CONFARCHIVO coma CONFA 
            {
              LinkedList<Instruccion> RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$Sintactico_O$stack.elementAt(CUP$Sintactico_O$top-2)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$Sintactico_O$stack.elementAt(CUP$Sintactico_O$top-2)).right;
		LinkedList<Instruccion> a = (LinkedList<Instruccion>)((java_cup.runtime.Symbol) CUP$Sintactico_O$stack.elementAt(CUP$Sintactico_O$top-2)).value;
		int bleft = ((java_cup.runtime.Symbol)CUP$Sintactico_O$stack.peek()).left;
		int bright = ((java_cup.runtime.Symbol)CUP$Sintactico_O$stack.peek()).right;
		Instruccion b = (Instruccion)((java_cup.runtime.Symbol) CUP$Sintactico_O$stack.peek()).value;
		RESULT=a; RESULT.add(b);
              CUP$Sintactico_O$result = parser.getSymbolFactory().newSymbol("CONFARCHIVO",8, ((java_cup.runtime.Symbol)CUP$Sintactico_O$stack.elementAt(CUP$Sintactico_O$top-2)), ((java_cup.runtime.Symbol)CUP$Sintactico_O$stack.peek()), RESULT);
            }
          return CUP$Sintactico_O$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // CONFARCHIVO ::= CONFA 
            {
              LinkedList<Instruccion> RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$Sintactico_O$stack.peek()).left;
		int aright = ((java_cup.runtime.Symbol)CUP$Sintactico_O$stack.peek()).right;
		Instruccion a = (Instruccion)((java_cup.runtime.Symbol) CUP$Sintactico_O$stack.peek()).value;
		RESULT = new LinkedList(); RESULT.add(a);
              CUP$Sintactico_O$result = parser.getSymbolFactory().newSymbol("CONFARCHIVO",8, ((java_cup.runtime.Symbol)CUP$Sintactico_O$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico_O$stack.peek()), RESULT);
            }
          return CUP$Sintactico_O$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // CONFA ::= nombre dospuntos cadena 
            {
              Instruccion RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$Sintactico_O$stack.elementAt(CUP$Sintactico_O$top-2)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$Sintactico_O$stack.elementAt(CUP$Sintactico_O$top-2)).right;
		String a = (String)((java_cup.runtime.Symbol) CUP$Sintactico_O$stack.elementAt(CUP$Sintactico_O$top-2)).value;
		int bleft = ((java_cup.runtime.Symbol)CUP$Sintactico_O$stack.peek()).left;
		int bright = ((java_cup.runtime.Symbol)CUP$Sintactico_O$stack.peek()).right;
		String b = (String)((java_cup.runtime.Symbol) CUP$Sintactico_O$stack.peek()).value;
		RESULT = new PROPIEDAD(a,b,aleft,aright);
              CUP$Sintactico_O$result = parser.getSymbolFactory().newSymbol("CONFA",9, ((java_cup.runtime.Symbol)CUP$Sintactico_O$stack.elementAt(CUP$Sintactico_O$top-2)), ((java_cup.runtime.Symbol)CUP$Sintactico_O$stack.peek()), RESULT);
            }
          return CUP$Sintactico_O$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // CONFA ::= fecha dospuntos cadena 
            {
              Instruccion RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$Sintactico_O$stack.elementAt(CUP$Sintactico_O$top-2)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$Sintactico_O$stack.elementAt(CUP$Sintactico_O$top-2)).right;
		String a = (String)((java_cup.runtime.Symbol) CUP$Sintactico_O$stack.elementAt(CUP$Sintactico_O$top-2)).value;
		int bleft = ((java_cup.runtime.Symbol)CUP$Sintactico_O$stack.peek()).left;
		int bright = ((java_cup.runtime.Symbol)CUP$Sintactico_O$stack.peek()).right;
		String b = (String)((java_cup.runtime.Symbol) CUP$Sintactico_O$stack.peek()).value;
		RESULT = new PROPIEDAD(a,b,aleft,aright);
              CUP$Sintactico_O$result = parser.getSymbolFactory().newSymbol("CONFA",9, ((java_cup.runtime.Symbol)CUP$Sintactico_O$stack.elementAt(CUP$Sintactico_O$top-2)), ((java_cup.runtime.Symbol)CUP$Sintactico_O$stack.peek()), RESULT);
            }
          return CUP$Sintactico_O$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // CARPETA ::= carpeta dospuntos abrirllave nombre dospuntos cadena coma DIRECTORIOS cerrarllave 
            {
              Instruccion RESULT =null;
		int nleft = ((java_cup.runtime.Symbol)CUP$Sintactico_O$stack.elementAt(CUP$Sintactico_O$top-8)).left;
		int nright = ((java_cup.runtime.Symbol)CUP$Sintactico_O$stack.elementAt(CUP$Sintactico_O$top-8)).right;
		String n = (String)((java_cup.runtime.Symbol) CUP$Sintactico_O$stack.elementAt(CUP$Sintactico_O$top-8)).value;
		int aleft = ((java_cup.runtime.Symbol)CUP$Sintactico_O$stack.elementAt(CUP$Sintactico_O$top-5)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$Sintactico_O$stack.elementAt(CUP$Sintactico_O$top-5)).right;
		String a = (String)((java_cup.runtime.Symbol) CUP$Sintactico_O$stack.elementAt(CUP$Sintactico_O$top-5)).value;
		int bleft = ((java_cup.runtime.Symbol)CUP$Sintactico_O$stack.elementAt(CUP$Sintactico_O$top-3)).left;
		int bright = ((java_cup.runtime.Symbol)CUP$Sintactico_O$stack.elementAt(CUP$Sintactico_O$top-3)).right;
		String b = (String)((java_cup.runtime.Symbol) CUP$Sintactico_O$stack.elementAt(CUP$Sintactico_O$top-3)).value;
		int cleft = ((java_cup.runtime.Symbol)CUP$Sintactico_O$stack.elementAt(CUP$Sintactico_O$top-1)).left;
		int cright = ((java_cup.runtime.Symbol)CUP$Sintactico_O$stack.elementAt(CUP$Sintactico_O$top-1)).right;
		LinkedList<Instruccion> c = (LinkedList<Instruccion>)((java_cup.runtime.Symbol) CUP$Sintactico_O$stack.elementAt(CUP$Sintactico_O$top-1)).value;
		RESULT = new CARPETA(a,b,c,nleft,nright);
              CUP$Sintactico_O$result = parser.getSymbolFactory().newSymbol("CARPETA",7, ((java_cup.runtime.Symbol)CUP$Sintactico_O$stack.elementAt(CUP$Sintactico_O$top-8)), ((java_cup.runtime.Symbol)CUP$Sintactico_O$stack.peek()), RESULT);
            }
          return CUP$Sintactico_O$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // CARPETA ::= carpeta dospuntos abrirllave DIRECTORIOS coma nombre dospuntos cadena cerrarllave 
            {
              Instruccion RESULT =null;
		int nleft = ((java_cup.runtime.Symbol)CUP$Sintactico_O$stack.elementAt(CUP$Sintactico_O$top-8)).left;
		int nright = ((java_cup.runtime.Symbol)CUP$Sintactico_O$stack.elementAt(CUP$Sintactico_O$top-8)).right;
		String n = (String)((java_cup.runtime.Symbol) CUP$Sintactico_O$stack.elementAt(CUP$Sintactico_O$top-8)).value;
		int cleft = ((java_cup.runtime.Symbol)CUP$Sintactico_O$stack.elementAt(CUP$Sintactico_O$top-5)).left;
		int cright = ((java_cup.runtime.Symbol)CUP$Sintactico_O$stack.elementAt(CUP$Sintactico_O$top-5)).right;
		LinkedList<Instruccion> c = (LinkedList<Instruccion>)((java_cup.runtime.Symbol) CUP$Sintactico_O$stack.elementAt(CUP$Sintactico_O$top-5)).value;
		int aleft = ((java_cup.runtime.Symbol)CUP$Sintactico_O$stack.elementAt(CUP$Sintactico_O$top-3)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$Sintactico_O$stack.elementAt(CUP$Sintactico_O$top-3)).right;
		String a = (String)((java_cup.runtime.Symbol) CUP$Sintactico_O$stack.elementAt(CUP$Sintactico_O$top-3)).value;
		int bleft = ((java_cup.runtime.Symbol)CUP$Sintactico_O$stack.elementAt(CUP$Sintactico_O$top-1)).left;
		int bright = ((java_cup.runtime.Symbol)CUP$Sintactico_O$stack.elementAt(CUP$Sintactico_O$top-1)).right;
		String b = (String)((java_cup.runtime.Symbol) CUP$Sintactico_O$stack.elementAt(CUP$Sintactico_O$top-1)).value;
		RESULT = new CARPETA(a,b,c,nleft,nright);
              CUP$Sintactico_O$result = parser.getSymbolFactory().newSymbol("CARPETA",7, ((java_cup.runtime.Symbol)CUP$Sintactico_O$stack.elementAt(CUP$Sintactico_O$top-8)), ((java_cup.runtime.Symbol)CUP$Sintactico_O$stack.peek()), RESULT);
            }
          return CUP$Sintactico_O$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // CARPETA ::= carpeta dospuntos abrirllave nombre dospuntos cadena cerrarllave 
            {
              Instruccion RESULT =null;
		int nleft = ((java_cup.runtime.Symbol)CUP$Sintactico_O$stack.elementAt(CUP$Sintactico_O$top-6)).left;
		int nright = ((java_cup.runtime.Symbol)CUP$Sintactico_O$stack.elementAt(CUP$Sintactico_O$top-6)).right;
		String n = (String)((java_cup.runtime.Symbol) CUP$Sintactico_O$stack.elementAt(CUP$Sintactico_O$top-6)).value;
		int aleft = ((java_cup.runtime.Symbol)CUP$Sintactico_O$stack.elementAt(CUP$Sintactico_O$top-3)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$Sintactico_O$stack.elementAt(CUP$Sintactico_O$top-3)).right;
		String a = (String)((java_cup.runtime.Symbol) CUP$Sintactico_O$stack.elementAt(CUP$Sintactico_O$top-3)).value;
		int bleft = ((java_cup.runtime.Symbol)CUP$Sintactico_O$stack.elementAt(CUP$Sintactico_O$top-1)).left;
		int bright = ((java_cup.runtime.Symbol)CUP$Sintactico_O$stack.elementAt(CUP$Sintactico_O$top-1)).right;
		String b = (String)((java_cup.runtime.Symbol) CUP$Sintactico_O$stack.elementAt(CUP$Sintactico_O$top-1)).value;
		RESULT = new CARPETA(a,b,null,nleft,nright);
              CUP$Sintactico_O$result = parser.getSymbolFactory().newSymbol("CARPETA",7, ((java_cup.runtime.Symbol)CUP$Sintactico_O$stack.elementAt(CUP$Sintactico_O$top-6)), ((java_cup.runtime.Symbol)CUP$Sintactico_O$stack.peek()), RESULT);
            }
          return CUP$Sintactico_O$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // CARPETA ::= carpeta dospuntos abrirllave nombre dospuntos cadena coma cerrarllave 
            {
              Instruccion RESULT =null;
		int nleft = ((java_cup.runtime.Symbol)CUP$Sintactico_O$stack.elementAt(CUP$Sintactico_O$top-7)).left;
		int nright = ((java_cup.runtime.Symbol)CUP$Sintactico_O$stack.elementAt(CUP$Sintactico_O$top-7)).right;
		String n = (String)((java_cup.runtime.Symbol) CUP$Sintactico_O$stack.elementAt(CUP$Sintactico_O$top-7)).value;
		int aleft = ((java_cup.runtime.Symbol)CUP$Sintactico_O$stack.elementAt(CUP$Sintactico_O$top-4)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$Sintactico_O$stack.elementAt(CUP$Sintactico_O$top-4)).right;
		String a = (String)((java_cup.runtime.Symbol) CUP$Sintactico_O$stack.elementAt(CUP$Sintactico_O$top-4)).value;
		int bleft = ((java_cup.runtime.Symbol)CUP$Sintactico_O$stack.elementAt(CUP$Sintactico_O$top-2)).left;
		int bright = ((java_cup.runtime.Symbol)CUP$Sintactico_O$stack.elementAt(CUP$Sintactico_O$top-2)).right;
		String b = (String)((java_cup.runtime.Symbol) CUP$Sintactico_O$stack.elementAt(CUP$Sintactico_O$top-2)).value;
		RESULT = new CARPETA(a,b,null,nleft,nright);
              CUP$Sintactico_O$result = parser.getSymbolFactory().newSymbol("CARPETA",7, ((java_cup.runtime.Symbol)CUP$Sintactico_O$stack.elementAt(CUP$Sintactico_O$top-7)), ((java_cup.runtime.Symbol)CUP$Sintactico_O$stack.peek()), RESULT);
            }
          return CUP$Sintactico_O$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number "+CUP$Sintactico_O$act_num+"found in internal parse table");

        }
    } /* end of method */

  /** Method splitting the generated action code into several parts. */
  public final java_cup.runtime.Symbol CUP$Sintactico_O$do_action(
    int                        CUP$Sintactico_O$act_num,
    java_cup.runtime.lr_parser CUP$Sintactico_O$parser,
    java.util.Stack            CUP$Sintactico_O$stack,
    int                        CUP$Sintactico_O$top)
    throws java.lang.Exception
    {
              return CUP$Sintactico_O$do_action_part00000000(
                               CUP$Sintactico_O$act_num,
                               CUP$Sintactico_O$parser,
                               CUP$Sintactico_O$stack,
                               CUP$Sintactico_O$top);
    }
}

}
